# Generated by Django 3.2.8 on 2021-10-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('messages', models.JSONField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
