# Generated by Django 3.2.8 on 2021-10-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_conversation_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
